### ISSUE TITLE
Demo link not working - https://douganderson444.github.io/rdx/

### ISSUE THREAD

**Issue by venu-prasath** [DougAnderson444/rdx#1]
An internal api is returning 404 - https://douganderson444.github.io/rdx/rdx.js

**Comment by DougAnderson444** [comment]
Where did you get this link?

The correct one is:

https://douganderson444.github.io/rdx/

**Comment by DougAnderson444** [comment]
Thanks for report all the same! Link WAS broken.

Fixed with https://github.com/DougAnderson444/rdx/commit/5ea98397c269f362053b77a0d61c49fab195285e
